nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmAuthToken: '${NPM_AUTH_TOKEN-}'

npmRegistries:
  'https://registry.yarnpkg.com':
    npmAuthToken: '${NPM_AUTH_TOKEN-}'

# For scoped packages:
npmScopes:
  navios:
    npmAuthToken: '${NPM_AUTH_TOKEN-}'
