import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  builderSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Builder',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'builder' }],
    },
    {
      type: 'category',
      label: 'React Query',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'react-query' }],
    },
  ],
}

export default sidebars
