import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  diSidebar: [
    'intro',
    {
      type: 'category',
      label: 'DI',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'di' }],
    },
    {
      type: 'category',
      label: 'DI React',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'di-react' }],
    },
  ],
}

export default sidebars
