import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  packagesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'HTTP Client',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'http' }],
    },
    {
      type: 'category',
      label: 'JWT',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'jwt' }],
    },
    {
      type: 'category',
      label: 'Schedule',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'schedule' }],
    },
    {
      type: 'category',
      label: 'XML Adapter',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'adapter-xml' }],
    },
  ],
}

export default sidebars
