import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  serverSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'overview' }],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Adapters',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'adapters' }],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'advanced' }],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'recipes' }],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'faq' }],
    },
  ],
}

export default sidebars
